### PR TITLE
Add a Twitter archive page

### PR DESCRIPTION
**Pull request by barentsen**
This PR adds a page which displays the 100 "most popular" messages tweeted during the workshop, with "most popular" defined as having at least 5 favourites or 5 retweets.

You can see the page rendered here: http://htmlpreview.github.io/?https://github.com/barentsen/python-in-astronomy.github.io/blob/twitter-archive/twitter-archive.html

Let me know what you think?

### CODE REVIEW

**Comment by astrofrog** [comment]
@barentsen - thanks for doing this so fast! I'm on a very slow connection today so the preview isn't working, but will check tonight. That made me think though, should we just use a static version of this page since it isn't going to change?

**Comment by barentsen** [comment]
Uhoh, the good old problem of saving stuff rendered by Javascript into static HTML.

I tried http://stackoverflow.com/questions/22739514/how-to-get-html-with-javascript-rendered-sourcecode-by-using-selenium but to no avail. Have to run now but should be able to have another look tonight.

(Or we ignore people with slow connections?)

**Comment by astrofrog** [comment]
@barentsen - ok, let's not worry about that.

One thought: would it be worth also providing a page with all tweets, which could be linked to from the main tweets page (the one in this PR) with a disclaimer that there are a lot of tweets?

**Comment by astrofrog** [comment]
I'll go ahead and merge this for now, and we can consider the 'full' page later - thanks for contributing this!

**Comment by barentsen** [comment]
Hey -- showing all tweets is available by searching for #pyastro15 on Twitter (which is what the first link on the page does).  I'm inclined not to bother with making our own 'full' page for that reason.  (Unless we want a static page to serve as an archive forever, but that's probably against Twitter T&C, and probably not worth the effort?)

**Comment by astrofrog** [comment]
@barentsent - sounds good - in that case let's just keep the current page as-is. Thanks!

**Pull request merged**
